version: '3'


tasks:
  # Install Go dependencies
  install:
    desc: Install project dependencies
    cmds:
      - go mod tidy

  # Install development dependencies (MacOS only)
  install_dev:
    desc: Install development dependencies
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/air-verse/air@latest
      - brew install go-task

  # Run tests
  test:
    desc: Run tests
    cmds:
      - go test ./...

  # Build the application
  build:
    desc: Build the Go application
    cmds:
      - go build -o bin/app ./cmd

  # Format Go code
  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  # Lint Go code
  lint:
    desc: Run Go linter
    cmds:
      - golangci-lint run

  # Start the application with live reloading using Air
  # Air https://github.com/air-verse/air
  start:
    desc: Start the application locally with live reload
    cmds:
      - DEBUG=true LOCAL=true air -c .air.toml

  # Run tests and then build the application
  test_and_build:
    desc: Run tests and then build the application
    cmds:
      - task test
      - task build
